In [129]:
import numpy as np
import pandas as pd

In [130]:
data = np.random.randn(4,3)

In [131]:
data

array([[ 0.56175934, -0.78538453, -0.083047  ],
       [ 0.23490791, -0.35775732, -1.11218055],
       [ 0.21872209,  0.84111684,  1.05969795],
       [-0.37516276,  1.17755281,  0.42467015]])

In [132]:
# series tek boyutlu basit dataları tutmak içindi. "pd.Series(data)" diyemeyiz hata verir. Burada data frame kullanacağız!!!!!

In [133]:
data_frame = pd.DataFrame(data)

In [134]:
data_frame

          0         1         2
0  0.561759 -0.785385 -0.083047
1  0.234908 -0.357757 -1.112181
2  0.218722  0.841117  1.059698
3 -0.375163  1.177553  0.424670

In [135]:
type(data_frame)

pandas.core.frame.DataFrame

In [136]:
type(data_frame[0])

pandas.core.series.Series

In [137]:
new_df = pd.DataFrame(data , index = ["Gökdeniz","Kayra","Fatih","Aleyna"], columns = ["Salary","Age","Seniority"])
# DATA FRAME OLUŞTURMA AŞAMASI -------------------

In [138]:
new_df

            Salary       Age  Seniority
Gökdeniz  0.561759 -0.785385  -0.083047
Kayra     0.234908 -0.357757  -1.112181
Fatih     0.218722  0.841117   1.059698
Aleyna   -0.375163  1.177553   0.424670

In [139]:
new_df["Seniority"]

Gökdeniz   -0.083047
Kayra      -1.112181
Fatih       1.059698
Aleyna      0.424670
Name: Seniority, dtype: float64

In [140]:
new_df[["Salary","Age"]]
# Yazım tipine dikkat!! --> Liste içinde liste gibi yazıyoruz...

            Salary       Age
Gökdeniz  0.561759 -0.785385
Kayra     0.234908 -0.357757
Fatih     0.218722  0.841117
Aleyna   -0.375163  1.177553

In [141]:
new_df.loc["Aleyna"] # Eğer row bazlı arama yapacaksak ---> .loc kullanmamız gerekir. Eğer new_df["Aleyna"] yapsaydım...
# Aleyna adında column olmadığı için hata alacaktım. Row olduğu için loc gerekiyor.

Salary      -0.375163
Age          1.177553
Seniority    0.424670
Name: Aleyna, dtype: float64

In [142]:
# new_df[0] --> şuanda çalışmaz çünkü rowlara farklı değerler atadık isimleri koyduk eğer index bazlı arama yapmak istiyorsak...

new_df.iloc[0]

Salary       0.561759
Age         -0.785385
Seniority   -0.083047
Name: Gökdeniz, dtype: float64

In [143]:
# 0. index elemanı olan "Gökdeniz" ' in columnlarındaki değerleri getirdi !!!

In [144]:
new_df.iloc[:,1]  # ---> ":" bütün rowları seç demek. sonrasında 1 dediğimde 1. sütundaki bütün değerleri getiriyor!

Gökdeniz   -0.785385
Kayra      -0.357757
Fatih       0.841117
Aleyna      1.177553
Name: Age, dtype: float64

In [145]:
new_df["Extra"] = 10
# Extra adında yeni bir kolon oluşturduk ve değerlerini 10 olarak atadık!

In [146]:
new_df

            Salary       Age  Seniority  Extra
Gökdeniz  0.561759 -0.785385  -0.083047     10
Kayra     0.234908 -0.357757  -1.112181     10
Fatih     0.218722  0.841117   1.059698     10
Aleyna   -0.375163  1.177553   0.424670     10

In [147]:
new_df.drop("Extra" , axis=1)
# Extra sütununu tamamen kaldırdı!;

# axis=0 → satır (row) bazlı işlem.
# axis=1 → sütun (column) bazlı işlem.

            Salary       Age  Seniority
Gökdeniz  0.561759 -0.785385  -0.083047
Kayra     0.234908 -0.357757  -1.112181
Fatih     0.218722  0.841117   1.059698
Aleyna   -0.375163  1.177553   0.424670

In [148]:
new_df

            Salary       Age  Seniority  Extra
Gökdeniz  0.561759 -0.785385  -0.083047     10
Kayra     0.234908 -0.357757  -1.112181     10
Fatih     0.218722  0.841117   1.059698     10
Aleyna   -0.375163  1.177553   0.424670     10

In [149]:
# new_df dediğimizde hala extra kolonu mevcut. Kalcı olarak kaldırmanın yolu ise şu --->

new_df.drop("Extra", axis = 1 , inplace = True)

In [150]:
new_df

            Salary       Age  Seniority
Gökdeniz  0.561759 -0.785385  -0.083047
Kayra     0.234908 -0.357757  -1.112181
Fatih     0.218722  0.841117   1.059698
Aleyna   -0.375163  1.177553   0.424670

In [151]:
# Gördüğümüz gibi "Extra" adlı kolon tamamen kaldırılmış oldu !!!

In [152]:
new_df["Aleyna"] = 10

In [153]:
new_df

            Salary       Age  Seniority  Aleyna
Gökdeniz  0.561759 -0.785385  -0.083047      10
Kayra     0.234908 -0.357757  -1.112181      10
Fatih     0.218722  0.841117   1.059698      10
Aleyna   -0.375163  1.177553   0.424670      10

In [154]:
new_df.drop("Aleyna")

            Salary       Age  Seniority  Aleyna
Gökdeniz  0.561759 -0.785385  -0.083047      10
Kayra     0.234908 -0.357757  -1.112181      10
Fatih     0.218722  0.841117   1.059698      10

In [155]:
# axis'in default değeri 0 olduğu için row'daki Aleynayı sildi!

In [156]:
new_df.drop("Aleyna", axis = 1 , inplace = True)

In [157]:
new_df

            Salary       Age  Seniority
Gökdeniz  0.561759 -0.785385  -0.083047
Kayra     0.234908 -0.357757  -1.112181
Fatih     0.218722  0.841117   1.059698
Aleyna   -0.375163  1.177553   0.424670

In [158]:
new_df.loc["Aleyna"]["Salary"]

# tek bir hücreyi bu şekilde çağırabiliriz.

np.float64(-0.3751627618623499)

In [159]:
new_df.loc["Aleyna","Salary"] = 100

In [160]:
new_df

              Salary       Age  Seniority
Gökdeniz    0.561759 -0.785385  -0.083047
Kayra       0.234908 -0.357757  -1.112181
Fatih       0.218722  0.841117   1.059698
Aleyna    100.000000  1.177553   0.424670

In [161]:
new_df[new_df>0]

              Salary       Age  Seniority
Gökdeniz    0.561759       NaN        NaN
Kayra       0.234908       NaN        NaN
Fatih       0.218722  0.841117   1.059698
Aleyna    100.000000  1.177553   0.424670

In [162]:
new_df[new_df["Salary"]>1]

        Salary       Age  Seniority
Aleyna   100.0  1.177553    0.42467

In [163]:
new_df[new_df["Age"]>0]

            Salary       Age  Seniority
Fatih     0.218722  0.841117   1.059698
Aleyna  100.000000  1.177553   0.424670

In [164]:
new_df.reset_index()  # Önemli bir fonksiyon!!!!!

# Daha önce verdiğimiz name indexlerini 0 1 2 3 rakamlarla indexleri değiştirdi. Artık numaralı indexlerle arama yapabiliriz.

      index      Salary       Age  Seniority
0  Gökdeniz    0.561759 -0.785385  -0.083047
1     Kayra    0.234908 -0.357757  -1.112181
2     Fatih    0.218722  0.841117   1.059698
3    Aleyna  100.000000  1.177553   0.424670

In [165]:
reset_frame = new_df.reset_index()

In [166]:
reset_frame

      index      Salary       Age  Seniority
0  Gökdeniz    0.561759 -0.785385  -0.083047
1     Kayra    0.234908 -0.357757  -1.112181
2     Fatih    0.218722  0.841117   1.059698
3    Aleyna  100.000000  1.177553   0.424670

In [167]:
reset_frame.loc[0]

index        Gökdeniz
Salary       0.561759
Age         -0.785385
Seniority   -0.083047
Name: 0, dtype: object

In [168]:
new_indices = ["Gök","Kay","Fat","Aly"]

In [169]:
new_df["NewIndex"] = new_indices

In [170]:
new_df

              Salary       Age  Seniority NewIndex
Gökdeniz    0.561759 -0.785385  -0.083047      Gök
Kayra       0.234908 -0.357757  -1.112181      Kay
Fatih       0.218722  0.841117   1.059698      Fat
Aleyna    100.000000  1.177553   0.424670      Aly

In [171]:
new_df.set_index("NewIndex", inplace=True)

# set_index ---> index ataması yapar !

In [172]:
new_df

              Salary       Age  Seniority
NewIndex
Gök         0.561759 -0.785385  -0.083047
Kay         0.234908 -0.357757  -1.112181
Fat         0.218722  0.841117   1.059698
Aly       100.000000  1.177553   0.424670

In [173]:
# MULTİ İNDEX

In [174]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park",]
second_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [175]:
zipped_index = list(zip(first_index,second_index))

In [176]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [177]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [178]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [179]:
# Şimdi bunu kullanarak data frame oluşturabiliriz...

In [180]:
sample_values = np.ones((6,2))

In [185]:
big_df = pd.DataFrame(sample_values , index = zipped_index , columns = ["Age","Salary"])

# BURASI ÇOK ÖNEMLİ !!!!!!!

In [182]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [183]:
print(big_df)

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [184]:
# Multi index data frameleri görüntülerken print kullanarak daha hiyerarşik yapıda görebiliriz !!!