In [66]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv("satis_verisi.csv", parse_dates=["Date"])

In [38]:
df

     OrderID       Date   Product  Quantity  Price    Category  Total
0          1 2023-04-13   Monitor         2   3400  Elektronik   6800
1          2 2023-12-15   Telefon         2   3775  Elektronik   7550
2          3 2023-09-28    Laptop         2   3154  Elektronik   6308
3          4 2023-04-17  Kulaklık         3   2243    Aksesuar   6729
4          5 2023-03-13    Tablet         3   1411  Elektronik   4233
..       ...        ...       ...       ...    ...         ...    ...
495      496 2023-11-21    Klavye         1   4437    Aksesuar   4437
496      497 2023-01-04    Tablet         4    101  Elektronik    404
497      498 2023-01-16   Monitor         2   2948  Elektronik   5896
498      499 2023-10-07  Kulaklık         1   4144    Aksesuar   4144
499      500 2023-12-02     Mouse         3   2049    Aksesuar   6147

[500 rows x 7 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   500 non-null    int64
 1   Date      500 non-null    datetime64[ns]
 2   Product   500 non-null    object
 3   Quantity  500 non-null    int64
 4   Price     500 non-null    int64
 5   Category  500 non-null    object
 6   Total     500 non-null    int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 27.5+ KB

In [40]:
df['Total'].sum() # Toplam satış tutarı

np.int64(3190227)

In [41]:
df['Price'].mean() # ortalama ürün fiyatı

np.float64(2603.33)

In [42]:
best_selling =  df.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(1)

# EN ÇOK SATILAN ÜRÜN!

In [43]:
best_selling

Product
Mouse    221
Name: Quantity, dtype: int64

In [44]:
df

     OrderID       Date   Product  Quantity  Price    Category  Total
0          1 2023-04-13   Monitor         2   3400  Elektronik   6800
1          2 2023-12-15   Telefon         2   3775  Elektronik   7550
2          3 2023-09-28    Laptop         2   3154  Elektronik   6308
3          4 2023-04-17  Kulaklık         3   2243    Aksesuar   6729
4          5 2023-03-13    Tablet         3   1411  Elektronik   4233
..       ...        ...       ...       ...    ...         ...    ...
495      496 2023-11-21    Klavye         1   4437    Aksesuar   4437
496      497 2023-01-04    Tablet         4    101  Elektronik    404
497      498 2023-01-16   Monitor         2   2948  Elektronik   5896
498      499 2023-10-07  Kulaklık         1   4144    Aksesuar   4144
499      500 2023-12-02     Mouse         3   2049    Aksesuar   6147

[500 rows x 7 columns]

In [45]:
total_sale = df.groupby('Category')['Total'].sum()
# kategoriye göre toplam satış!

In [46]:
total_sale

Category
Aksesuar      1353147
Elektronik    1837080
Name: Total, dtype: int64

In [47]:
df['Date'] = pd.to_datetime(df['Date']) 
# Date kolonunu datetime yaptık!

In [48]:
df

     OrderID       Date   Product  Quantity  Price    Category  Total
0          1 2023-04-13   Monitor         2   3400  Elektronik   6800
1          2 2023-12-15   Telefon         2   3775  Elektronik   7550
2          3 2023-09-28    Laptop         2   3154  Elektronik   6308
3          4 2023-04-17  Kulaklık         3   2243    Aksesuar   6729
4          5 2023-03-13    Tablet         3   1411  Elektronik   4233
..       ...        ...       ...       ...    ...         ...    ...
495      496 2023-11-21    Klavye         1   4437    Aksesuar   4437
496      497 2023-01-04    Tablet         4    101  Elektronik    404
497      498 2023-01-16   Monitor         2   2948  Elektronik   5896
498      499 2023-10-07  Kulaklık         1   4144    Aksesuar   4144
499      500 2023-12-02     Mouse         3   2049    Aksesuar   6147

[500 rows x 7 columns]

In [49]:
monthly_sales = df.groupby(df['Date'].dt.month)['Total'].sum()
# Datetime olan date kolonundan dt.month ile ay kısmına göre grupladık ve Total satışı hesapladık

In [50]:
monthly_sales

Date
1     209758
2     346130
3     116103
4     337067
5     266138
6     261477
7     236190
8     332964
9     240456
10    255398
11    287467
12    301079
Name: Total, dtype: int64

In [51]:
df = df.set_index("Date")

# date sütununu index yaptık!

In [52]:
# Belirli tarih aralıklarındaki satışları analiz etmek istiyoruz diyelim. Mesela yaz satışlar 1 haziran 31 ağustos arası olsun

In [53]:
df

            OrderID   Product  Quantity  Price    Category  Total
Date
2023-04-13        1   Monitor         2   3400  Elektronik   6800
2023-12-15        2   Telefon         2   3775  Elektronik   7550
2023-09-28        3    Laptop         2   3154  Elektronik   6308
2023-04-17        4  Kulaklık         3   2243    Aksesuar   6729
2023-03-13        5    Tablet         3   1411  Elektronik   4233
...             ...       ...       ...    ...         ...    ...
2023-11-21      496    Klavye         1   4437    Aksesuar   4437
2023-01-04      497    Tablet         4    101  Elektronik    404
2023-01-16      498   Monitor         2   2948  Elektronik   5896
2023-10-07      499  Kulaklık         1   4144    Aksesuar   4144
2023-12-02      500     Mouse         3   2049    Aksesuar   6147

[500 rows x 6 columns]

In [56]:
df = df.sort_index()
yaz_ayi_satislari = df.loc["2023-06-01":"2023-08-31"]

In [59]:
yaz_ayi_satislari

            OrderID   Product  Quantity  Price    Category  Total
Date
2023-06-01      190  Kulaklık         2    138    Aksesuar    276
2023-06-01      277     Mouse         4    102    Aksesuar    408
2023-06-01       15    Tablet         1    874  Elektronik    874
2023-06-02      290    Laptop         3   1740  Elektronik   5220
2023-06-02      396    Tablet         3    128  Elektronik    384
...             ...       ...       ...    ...         ...    ...
2023-08-27      448    Laptop         4   1150  Elektronik   4600
2023-08-28      232   Monitor         3    475  Elektronik   1425
2023-08-29      142    Klavye         4   4207    Aksesuar  16828
2023-08-30       52     Mouse         4   4133    Aksesuar  16532
2023-08-31      156    Tablet         4    588  Elektronik   2352

[128 rows x 6 columns]

In [60]:
# Customer verisi
data = {
    "CustomerID": ["C001", "C002", "C003", "C004", "C005"],
    "Name": ["Ali", "Ayşe", "Mehmet", "Zeynep", "Ahmet"],
    "City": ["İstanbul", "Ankara", "İzmir", "Bursa", "Antalya"]
}

customers = pd.DataFrame(data)

# CSV olarak kaydet
customers.to_csv("customer.csv", index=False)

In [61]:
df2 = pd.read_csv('customer.csv')

In [64]:
df2

  CustomerID    Name      City
0       C001     Ali  İstanbul
1       C002    Ayşe    Ankara
2       C003  Mehmet     İzmir
3       C004  Zeynep     Bursa
4       C005   Ahmet   Antalya

In [70]:
df['CustomerID'] = np.random.choice(['C001', 'C002', 'C003', 'C004', 'C005'], size=len(df))

In [72]:
df

            OrderID   Product  Quantity  Price    Category  Total CustomerID
Date
2023-01-01      447     Mouse         4    690    Aksesuar   2760       C005
2023-01-02      264    Laptop         2   3945  Elektronik   7890       C005
2023-01-02      207     Mouse         4   3312    Aksesuar  13248       C002
2023-01-02       64    Tablet         3    904  Elektronik   2712       C003
2023-01-04      497    Tablet         4    101  Elektronik    404       C003
...             ...       ...       ...    ...         ...    ...        ...
2023-12-26       63    Laptop         2   3898  Elektronik   7796       C002
2023-12-26      252  Kulaklık         2   1968    Aksesuar   3936       C002
2023-12-30       38   Telefon         4   1487  Elektronik   5948       C005
2023-12-31      313  Kulaklık         2   4788    Aksesuar   9576       C004
2023-12-31      420   Monitor         1   3878  Elektronik   3878       C002

[500 rows x 7 columns]

In [73]:
df = pd.merge(df,df2, on = "CustomerID" , how = "left")

In [74]:
df

,OrderID,Product,Quantity,Price,Category,Total,CustomerID,Name,City
0,447,Mouse,4,690,Aksesuar,2760,C005,Ahmet,Antalya
1,264,Laptop,2,3945,Elektronik,7890,C005,Ahmet,Antalya
2,207,Mouse,4,3312,Aksesuar,13248,C002,Ayşe,Ankara
3,64,Tablet,3,904,Elektronik,2712,C003,Mehmet,İzmir
4,497,Tablet,4,101,Elektronik,404,C003,Mehmet,İzmir
...,...,...,...,...,...,...,...,...,...
495,63,Laptop,2,3898,Elektronik,7796,C002,Ayşe,Ankara
496,252,Kulaklık,2,1968,Aksesuar,3936,C002,Ayşe,Ankara
497,38,Telefon,4,1487,Elektronik,5948,C005,Ahmet,Antalya
498,313,Kulaklık,2,4788,Aksesuar,9576,C004,Zeynep,Bursa
499,420,Monitor,1,3878,Elektronik,3878,C002,Ayşe,Ankara

In [75]:
def discount(price):
    return price * 0.9  # %10 indirim

In [76]:
df['Discount Price'] = df['Price'].apply(discount)

In [77]:
df

,OrderID,Product,Quantity,Price,Category,Total,CustomerID,Name,City,Discount Price
0,447,Mouse,4,690,Aksesuar,2760,C005,Ahmet,Antalya,621.0
1,264,Laptop,2,3945,Elektronik,7890,C005,Ahmet,Antalya,3550.5
2,207,Mouse,4,3312,Aksesuar,13248,C002,Ayşe,Ankara,2980.8
3,64,Tablet,3,904,Elektronik,2712,C003,Mehmet,İzmir,813.6
4,497,Tablet,4,101,Elektronik,404,C003,Mehmet,İzmir,90.9
...,...,...,...,...,...,...,...,...,...,...
495,63,Laptop,2,3898,Elektronik,7796,C002,Ayşe,Ankara,3508.2
496,252,Kulaklık,2,1968,Aksesuar,3936,C002,Ayşe,Ankara,1771.2
497,38,Telefon,4,1487,Elektronik,5948,C005,Ahmet,Antalya,1338.3
498,313,Kulaklık,2,4788,Aksesuar,9576,C004,Zeynep,Bursa,4309.2
499,420,Monitor,1,3878,Elektronik,3878,C002,Ayşe,Ankara,3490.2

In [78]:
df.to_csv("analiz_sonuclari.csv", index=False)